FiorelloFrontBackDB/Controllers/HomeController.cs
    using FiorelloFrontBackDB.Data;
using FiorelloFrontBackDB.Models;
using FiorelloFrontBackDB.Services.Interfaces;
using FiorelloFrontBackDB.ViewModels;
using FiorelloFrontBackDB.ViewModels.Baskets;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Diagnostics;

namespace FiorelloFrontBackDB.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IExpertService _expertService;
        private readonly ISliderInstaService _sliderInstaService;
        private readonly IBlogService _blogService;
        private readonly IHttpContextAccessor _accessor;

        public HomeController(AppDbContext context,
                              IProductService productService,
                              ICategoryService categoryService,
                              IExpertService expertService,
                              ISliderInstaService sliderInstaService,
                              IBlogService blogService,IHttpContextAccessor accessor)
        {
            _context = context; 
            _productService = productService;
            _categoryService = categoryService;
            _expertService = expertService;
            _sliderInstaService = sliderInstaService;
            _blogService = blogService;
            _accessor = accessor;
        }
        public async Task<IActionResult> Index()
        {
            List<Category> categories = await _categoryService.GetAllAsync();
            List<Product> products = await _productService.GetAllWithImagesAsync();
            About aboutParts = await _context.AboutParts.FirstOrDefaultAsync();
            List<Position> positions = await _context.Positions.ToListAsync();
            List<Expert> experts = await _expertService.GetAllAsync();
            List<Blog> blogs = await _blogService.TakeAsync();
            List<InstaSlider> instaSliders = await _sliderInstaService.GetAllAsync();
            HomeVM model = new()
            {
                Categories = categories,
                Products = products,
                AboutParts = aboutParts,
                Experts = experts,
                Positions = positions,
                Blogs = blogs,
                InstaSliders = instaSliders
            };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddProductToBasket(int? id)
        {
            if (id is null) return BadRequest();

            List<BasketVM> basketProducts = null;

            if (_accessor.HttpContext.Request.Cookies["basket"] is not null)
            {
                basketProducts = JsonConvert.DeserializeObject<List<BasketVM>>(_accessor.HttpContext.Request.Cookies["basket"]);
            }
            else
            {
                basketProducts = new List<BasketVM>();
            }


            var dbProduct = await _productService.GetByIdAsync((int)id);


            var existProduct = basketProducts.FirstOrDefault(m => m.Id == (int)id);

            if (existProduct is not null)
            {
                existProduct.Count++;
            }
            else
            {   
                basketProducts.Add(new BasketVM
                {
                    Id = (int)id,
                    Count = 1,
                    Price = dbProduct.Price
                });
            }  


            _accessor.HttpContext.Response.Cookies.Append("basket",JsonConvert.SerializeObject(basketProducts));

            int count = basketProducts.Sum(m=> m.Count);    
            decimal totalPrice = basketProducts.Sum(m=> m.Count * m.Price);    

            return Ok(new {count, totalPrice});
        }
    }
}

FiorelloFrontBackDB/Controllers/ProductController.cs
using FiorelloFrontBackDB.Data;
using FiorelloFrontBackDB.Models;
using FiorelloFrontBackDB.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FiorelloFrontBackDB.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public async Task<IActionResult> Index(int? id)
        {
            if(id is null)
            {
                return BadRequest();
            }
            Product product = await _productService.GetByIdAsync((int)id);

            if(product is null)
            {
                return NotFound();  
            }
            return View(product);
        }
    }
}

FiorelloFrontBackDB/ViewComponents/SliderViewComponent.cs
using FiorelloFrontBackDB.Data;
using FiorelloFrontBackDB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FiorelloFrontBackDB.ViewComponents
{
    public class SliderViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;
        public SliderViewComponent(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var sliderData = new SliderVMVC
            {
                Sliders = await _context.Sliders.ToListAsync(),
                SliderInfo = await _context.SliderInfos.FirstOrDefaultAsync()
            };

            return await Task.FromResult(View(sliderData)); 
        }
    }

    public class SliderVMVC 
    {
        public List<Slider> Sliders { get; set; }
        public SliderInfo SliderInfo { get; set; }

    }
}

FiorelloFrontBackDB/Views/Home/Index.cshtml
@model HomeVM   


<!-- MAIN START -->

    <main>

        <!-- SLIDER START -->

        @await Component.InvokeAsync("Slider")

        <!-- SLIDER END -->

        <!-- PRODUCTS START -->

        <section id="products">
            <div class="container">
                <div class="row pt-5">
                    <div class="col-12 d-flex justify-content-between">
                        <ul class="category-mobile d-md-none list-unstyled">
                            <li>
                                <a href="" class="categories mr-2">Categories</a>
                                <i class="fas fa-caret-down"></i>
                                <ul class="category list-unstyled" style="display: none;">
                                    <li><a href="" data-id="all">All</a></li>
                            @foreach (var item in Model.Categories)
                        {
                            <li><a href="" data-id="@item.Id">@item.Name</a></li>
                        }
                                </ul>
                            </li>
                        </ul>
                        <ul class="category d-none d-md-flex list-unstyled">
                            <li><a href="" data-id="all">All</a></li>
                            @foreach (var item in Model.Categories)
                        {
                            <li><a href="" data-id="@item.Id">@item.Name</a></li>
                        }
                        </ul>
                        <ul class="list-unstyled">
                            <li>
                                <a href="" class="mr-2">Filter</a>
                                <i class="fas fa-caret-down"></i>
                            </li>
                        </ul>
                    </div>
                </div>  
                <div class="row">
                    @foreach (var item in Model.Products)
                {
                    <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
                        <div class="product-item text-center" data-id="@item.CategoryId">
                            <div class="img">
                                <a asp-controller="Product" asp-action="Index" asp-route-id="@item.Id">
                                    <img src="~/img/@item.ProductImages.FirstOrDefault(m=> m.IsMain = true).ImageUrl" class="img-fluid" alt="">
                                </a>   
                            </div>   
                            <div class="title mt-3">   
                                <h6>@item.Name</h6>   
                            </div>   
                            <div class="price">
                                <span class="text-black-50 add-product-basket" data-id="@item.Id">Add to cart</span> 
                                <span class="text-black-50">$@item.Price</span>   
                            </div>   
                        </div>
                    </div>

                }
                </div>
            </div>
        </section>

        <!-- PRODUCTS END -->

        <!-- ABOUT START -->

        <section id="about">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-lg-6">
                        <div class="img">
                            <img src="~/img/@Model.AboutParts.AboutMainImage" class="img-fluid" alt="">
                            <div
                                class="player position-absolute rounded-circle d-flex align-items-center justify-content-center">
                                <i class="fas fa-play fa-lg"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about-text mt-5 mt-lg-0 px-lg-5">
                            @Html.Raw(Model.AboutParts.AboutTitle)
                            <p class="py-3">@Model.AboutParts.AboutDescription</p>
                            <ul class="list-unstyled">
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt="">@Model.AboutParts.AboutListProperty1</li class="mt-3">
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt="">@Model.AboutParts.AboutListProperty2</li>
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt="">@Model.AboutParts.AboutListProperty3</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ABOUT END -->

        <!-- EXPERTS START -->

        <section id="experts">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>Flower Experts</h1>
                            <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                                love. Let us arrange
                                a smile for you.</p>
                        </div>
                    </div>
                </div>
                <div class="row pb-5">
                    @foreach (var item in Model.Experts.Take(4))
                {
                    <div class="col-md-6 col-lg-3">
                        <div class="item text-center">
                            <div class="img">
                                <img src="~/img/@item.ExpertImages.FirstOrDefault(m => m.IsMain= true).ExpertImageUrl" class="img-fluid rounded-circle" alt="">
                            </div>
                            <div class="text mt-3">
                                <h6>@item.FullName</h6>
                                <p class="text-black-50">@item.Position.PostionName</p>
                            </div>
                        </div>
                    </div>
                }
                    
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                </div>
            </div>
        </section>

        <!-- EXPERTS END -->

        <!-- SUBSCRIBE START -->

        <section id="subscribe">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-12">
                        <div class="content text-center py-5">
                            <h3>Join The Colorful Bunch!</h3>
                            <div class="form-group d-flex justify-content-center flex-wrap mt-5">
                                <input type="email" placeholder="Email Address" class="form-control-lg rounded-0">
                                <button class="btn btn-danger btn-lg rounded-0 px-5 mt-3 mt-sm-0">Subscribe</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SUBSCRIBE END -->

        <!-- BLOG START -->
        <section id="blog">
    <div class="container">
        <div class="row py-5">
            <div class="offset-lg-3 col-lg-6">
                <div class="section-title">
                    <h1>From our Blog</h1>
                    <p class="text-black-50">
                        A perfect blend of creativity, energy, communication, happiness and
                        love. Let us arrange
                        a smile for you.
                    </p>
                </div>
            </div>
        </div>
        <div class="row pb-5">
            <partial name="_BlogsPartial" model="Model.Blogs"/>
        </div>
    </div>
</section>

        

        <!-- BLOG END -->

        <!-- SAY START -->

        <section id="say">
            <div class="container">
                <div class="row py-5 justify-content-center">
                    <div class="col-md-8 col-xl-6">
                        <div class="owl-carousel say">
                            @foreach (var item in Model.Experts.Skip(4).Take(2))
                        {
                            <div>
                                <div class="item text-center">
                                    <div class="img d-flex justify-content-center">
                                        <img src="~/img/@item.ExpertImages.FirstOrDefault(m=>m.IsMain).ExpertImageUrl" alt="">
                                    </div>
                                    <div class="text text-muted pt-3 pb-5">
                                        <i>@item.ExpertOpinion</i>
                                    </div>
                                    <div class="author">
                                        <h6>@item.FullName</h6>
                                        <p class="text-black-50">@item.Position.PostionName</p>
                                    </div>
                                </div>
                            </div>
                        }
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SAY END -->

        <!-- INSTAGRAM START -->

        <section id="instagram">
            <div class="owl-carousel instagram">
                @foreach (var item in Model.InstaSliders)
            {
                <div><img src="~/img/@item.Image" class="img-fluid" alt=""></div>
            }
            </div>
            <div class="hastag bg-light text-muted py-2 px-3">
                #FIORELLO
            </div>
        </section>

        <!-- INSTAGRAM END -->

    </main>

    <!-- MAIN END -->